[package]
name = "bin_calc"
version = "0.1.0"
authors = ["Edoren"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
num-bigint = "0.2.6"
num-traits = "0.2.11"
